apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ecommerce-prod
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:mysql://ecommerce-mysql-primary.ch2kskk2c7ut.eu-west-1.rds.amazonaws.com:3306/ecommercedb?useSSL=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: admin
  MYSQL_DATABASE: ecommercedb
  SERVER_PORT: "8080"
  LOGGING_LEVEL_ROOT: INFO
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"           
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"