apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ecommerce-prod
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:mysql://<rdsendpoint>:3306/ecommercedb?useSSL=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: admin
  MYSQL_DATABASE: ecommercedb
  SERVER_PORT: "8080"
  LOGGING_LEVEL_ROOT: INFO
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus