apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: ecommerce-prod
type: Opaque
data:
  # echo -n 'YourPassword' | base64
  SPRING_DATASOURCE_PASSWORD: WW91clN1cGVyU2VjcmV0UGFzc3dvcmQxMjMh
  JWT_SECRET: c3VwZXJzZWNyZXRrZXkxMjM=